apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::023960176222:role/few_dyke.arc-EKS-AMP-ServiceAccount-Role
    meta.helm.sh/release-name: promethus-for-arcade
    meta.helm.sh/release-namespace: prometheus
  creationTimestamp: "2022-07-22T15:22:55Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.10.5
    component: server
    heritage: Helm
    release: promethus-for-arcade
  name: iamproxy-service-account
  namespace: prometheus
  resourceVersion: "2281593"
  uid: 4d59aa17-0873-480b-bfe1-9c12efae0ab6
secrets:
- name: iamproxy-service-account-token-tdz98
